import os

SVG = dict()

def cleanJavacriptVariableName(text: str):
    return text.upper().replace(
        " ", ""
    ).replace(
        "-", ""
    )

def compileFolder(path: str, name: str):
    name = name.upper()
    items = os.listdir(path)

    for item in items:
        item_path = os.path.join(path, item)
        
        if os.path.isdir(item_path):
            compileFolder(item_path, cleanJavacriptVariableName(f"{name}_{item}"))
        elif os.path.isfile(item_path):
            filename, ext = os.path.splitext(item)
            if ext == ".svg":
                with open(item_path, "r") as file:
                    svg = file.read()
                    SVG[cleanJavacriptVariableName(f"{name}_{filename}")] = svg 

def writeToJS(filename:str="icons.js"):
    res = "// rubbie kelvin voltsman\n/* DO NOT EDIT THIS FILE...\nCHANGES MADE TO THIS FILE WILL BE LOST\n*/\n"
    for key, value in SVG.items():
        res += f"var {key} = `{value}`\n"
    
    with open(filename, "w") as file:
        file.write(res)

compileFolder("/home/rubbiekelvin/Projects/CloudNote/mobile/uix/assets/icons/", "ICON")
writeToJS(filename="/home/rubbiekelvin/Projects/CloudNote/mobile/uix/scripts/frozen/icon.js")
